name: app_links_linux
description: Linux platform implementation of app_links plugin.
version: 1.0.4
homepage: https://github.com/llfbandit/app_links/tree/main/app_links_linux

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  
  app_links_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: app_links
    platforms:
      linux:
        pluginClass: AppLinksPluginLinux
